if( 0 ~= 0) then return end

local debug = false

MyLocalization = setmetatable(
	{
		['WoW Poker Lerduzz'] = 'WoW Poker Lerduzz',
		['Learn How to Play Texas Holdem'] = 'Aprende a jugar poker',
		['Quit'] = 'Salir',
		['Sit Out'] = 'Levantarse',
		['Play'] = 'Jugar',
		['Fold'] = 'Retirarse',
		['Call'] = 'Igualar',
		['All In'] = 'Jugar todo',
		['Raise'] = 'Subir',
		['Clear Chips'] = 'Limpiar fichas',
		['Chips'] = 'Fichas',
		['+100 Chips'] = '+100 Fichas',
		['Boot'] = 'Boot',
		['Ok'] = 'Ok',
		
		['Two'] = 'Dos',
		['Three'] = 'Tres',
		['Four'] = 'Cuatro',
		['Five'] = 'Cinco',
		['Six'] = 'Seis',
		['Seven'] = 'Siete',
		['Eight'] = 'Ocho',
		['Nine'] = 'Nueve',
		['Ten'] = 'Diez',
		['Jack'] = 'Jota',
		['Queen'] = 'Reina',
		['King'] = 'Rey',
		['Ace'] = 'Az',
		['Twos'] = 'Dos',
		['Threes'] = 'Tres',
		['Fours'] = 'Cuatros',
		['Fives'] = 'Cincos',
		['Sixes'] = 'Seis',
		['Sevens'] = 'Sietes',
		['Eights'] = 'Ochos',
		['Nines'] = 'Nueves',
		['Tens'] = 'Diez',
		['Jacks'] = 'Jotas',
		['Queens'] = 'Reinas',
		['Kings'] = 'Reyes',
		['Aces'] = 'Aces',	
		
		['High Card'] = 'Carta alta',
		['2 of a Kind'] = 'Pareja',
		['2 Pair'] = 'Dos parejas',
		['3 of a Kind'] = 'Trío',
		['Straight'] = 'Escalera',
		['Flush'] = 'Color',
		['Full House'] = 'Full',
		['4 of a Kind'] = 'Poker',
		['Flush Straight'] = 'Escalera de color',
		['Royal Flush'] = 'Escalera real',
		['%s full of %s'] = '%s full of %s',
		['Straight Flush to the %s'] = 'Straight Flush to the %s',
		['Flush: %s high'] = 'Color: %s (carta mayor)',
		['Straight to the %s'] = 'Straight to the %s',
		['%s over %s'] = '%s sobre %s',
		
		["Do you wish to start Dealing?"] = '¿Deseas comenzar la partida?',
		["To join a game use '/holdem dealer <playername>'"] = "Para unirte a un juego usa '/holdem dealer <playername>'",
		['Start Dealing'] = 'Comenzar',
		['Cancel'] = 'Cancelar',
		['Options'] = 'Opciones',
		['a Fork of AnzacHoldem'] = 'a Fork of AnzacHoldem',
		['Use \'/holdem\' to start a table as the dealer.'] = 'Use \'/holdem\' to start a table as the dealer.',
		['Use \'/holdem dealer <playername>\' to join someone elses table.'] = 'Use \'/holdem dealer <playername>\' to join someone elses table.',
		['Use \'/holdem artwork <number>\' to set artwork.'] = 'Use \'/holdem artwork <number>\' to set artwork.',
		['Use \'/holdem blind <number>\' to set starting blind.'] = 'Use \'/holdem blind <number>\' to set starting blind.',
		['Use \'/holdem increase <percent>\' to set blind increment percent.'] = 'Use \'/holdem increase <percent>\' to set blind increment percent.',
		['Use \'/holdem options\' for options panel'] = 'Use \'/holdem options\' for options panel',
		['AutoDealing'] = 'AutoDealing',
		['I\'m Back'] = 'I\'m Back',
		['Sit Out'] = 'Sit Out',
		['Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal.'] = 'Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal.',
		['Show Cards'] = 'Show Cards',
		['%s has seated you in Seat %d'] = '%s has seated you in Seat %d',
		['Check'] = 'Check',
		['Use just /holdem instead'] = 'Use just /holdem instead',
		['You did not act in time. Press I\'m Back to continue playing.'] = 'You did not act in time. Press I\'m Back to continue playing.',
		['has left the table.'] = 'has left the table.',
		['The dealer booted you.'] = 'The dealer booted you.',
		['has quit. GG.'] = 'has quit. GG.',
		['You are now a dealer.'] = 'You are now a dealer.',
		['Total Pot'] = 'Total Pot',
		['wins'] = 'wins',
		['Split'] = 'Split',
		['No Winners. Game Seed = '] = 'No Winners. Game Seed = ',
		['Error case'] = 'Error case',
		['Player Invalid Action'] = 'Player Invalid Action',
		['Cannot boot the dealer.'] = 'Cannot boot the dealer.',
		['Folded'] = 'Folded',
		['Showing'] = 'Showing',
		['No such player'] = 'No such player',
		['Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal.'] = 'Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal.',
		['WoW Poker Lerduzz Options'] = 'WoW Poker Lerduzz Options',
		['These options are saved between sessions'] = 'These options are saved between sessions',
		['Neutral'] = 'Neutral',
		['Alliance'] = 'Alliance',
		['Horde'] = 'Horde',
		['Original'] = 'Original',
		['Artwork'] = 'Artwork',
		['Select card back artwork'] = 'Select card back artwork',
		['Starting Chips'] = 'Starting Chips',
		['Set the starting Chips'] = 'Set the starting Chips',
		['Blind increase percent per round'] = 'Blind increase percent per round',
		['Set the by what percent the Blind increases each round'] = 'Set the by what percent the Blind increases each round',
		['Starting Blind'] = 'Starting Blind',
		['Set the starting Blind'] = 'Set the starting Blind',
		['Blinds'] = 'Blinds',
		['Small Blind'] = 'Small Blind',
		['Big Blind'] = 'Big Blind',
		['Checked'] = 'Checked',
		['Called'] = 'Called',
		['Raised'] = 'Raised',
		['Playing'] = 'Playing',
		['Sitting Out'] = 'Sitting Out',
		['Winner!'] = 'Winner!',
		['Default'] = 'Default',
		['Showdown'] = 'Showdown',
		['Feedback: www.FreeHoldemStrategy.com/forum/'] = 'Feedback: www.FreeHoldemStrategy.com/forum/',
		['Next Round\'s Big Blind'] = 'Next Round\'s Big Blind',
		['Current Blind Increment per round'] = 'Current Blind Increment per round',
		['%s sits %s in Seat %d'] = '%s sits %s in Seat %d',
		['Your turn'] = 'Your turn',
		['Minimap Icon'] = 'Minimap Icon',
		['Turn minimap icon on/off'] = 'Turn minimap icon on/off',
		['%s has no seat available for you'] = '%s has no seat available for you',
		['%s is a dealer and has %s seats available'] = '%s is a dealer and has %s seats available',
		['%s has client version %s'] = '%s has client version %s',
		['Use \'/holdem dealers\' to find dealers in your guild/party/raid.'] = 'Use \'/holdem dealers\' to find dealers in your guild/party/raid.',
		['Use \'/holdem clients\' to find clients in your guild/party/raid.'] = 'Use \'/holdem clients\' to find clients in your guild/party/raid.',
		['Use \'/holdem help\' for slash command options'] = 'Use \'/holdem help\' for slash command options',
		['Looking for dealers'] = 'Looking for dealers',
		['Looking for clients'] = 'Looking for clients',
		['Tick to act automatically'] = 'Tick to automatically act',
		['Call any'] = 'Call any',
		['Sticky'] = 'Sticky',
	}
	,
	{__index = function(self, key)
		if debug then ChatFrame3:AddMessage('Please localize: '..tostring(key)) end
		rawset(self, key, key)
		return key
	end
	}
)
