if( 0 ~= 0) then return end

local debug = false

MyLocalization = setmetatable(
	{
		['WoW Poker Lerduzz'] = 'WoW Poker Lerduzz',
		['Quit'] = 'Quit',
		['Sit Out'] = 'Sit Out',
		['Play'] = 'Play',
		['Fold'] = 'Fold',
		['Call'] = 'Call',
		['All In'] = 'All In',
		['Raise'] = 'Raise',
		['Chips'] = 'Chips',

		['Two'] = 'Two',
		['Three'] = 'Three',
		['Four'] = 'Four',
		['Five'] = 'Five',
		['Six'] = 'Six',
		['Seven'] = 'Seven',
		['Eight'] = 'Eight',
		['Nine'] = 'Nine',
		['Ten'] = 'Ten',
		['Jack'] = 'Jack',
		['Queen'] = 'Queen',
		['King'] = 'King',
		['Ace'] = 'Ace',
		['Twos'] = 'Twos',
		['Threes'] = 'Threes',
		['Fours'] = 'Fours',
		['Fives'] = 'Fives',
		['Sixes'] = 'Sixs',
		['Sevens'] = 'Sevens',
		['Eights'] = 'Eights',
		['Nines'] = 'Nines',
		['Tens'] = 'Tens',
		['Jacks'] = 'Jacks',
		['Queens'] = 'Queens',
		['Kings'] = 'Kings',
		['Aces'] = 'Aces',	
		
		['High Card'] = 'High Card',
		['1 Pair'] = '1 Pair',
		['2 Pair: %s, %s'] = '2 Pair: %s, %s',
		['3 of a Kind'] = '3 of a Kind',
		['Straight: %s (high)'] = 'Straight: %s (high)',
		['Flush: %s (high)'] = 'Flush: %s (high)',
		['Full House: %s, %s'] = 'Full House: %s, %s',
		['4 of a Kind'] = '4 of a Kind',
		['Straight Flush: %s (high)'] = 'Straight Flush: %s (high)',
		['Royal Flush'] = 'Royal Flush',
		
		["Do you want to start the game?"] = 'Do you want to start the game?',
		['Start Dealing'] = 'Start Dealing',
		['Cancel'] = 'Cancel',
		['Options'] = 'Options',
		['I\'m Back'] = 'I\'m Back',
		['Sit Out'] = 'Sit Out',
		['Show Cards'] = 'Show Cards',
		['%s has seated you in Seat %d'] = '%s has seated you in Seat %d',
		['Check'] = 'Check',
		['Use just /poker instead'] = 'Use just /poker instead',
		['You did not act in time. Press I\'m Back to continue playing.'] = 'You did not act in time. Press I\'m Back to continue playing.',
		['has left the table.'] = 'has left the table.',
		['Total Pot'] = 'Total Pot',
		['wins'] = 'wins',
		['Split'] = 'Split',
		['Folded'] = 'Folded',
		['Showing'] = 'Showing',
		['No such player'] = 'No such player',
		['WoW Poker Lerduzz Options'] = 'WoW Poker Lerduzz Options',
		['These options are saved between sessions'] = 'These options are saved between sessions',
		['Starting Chips'] = 'Starting Chips',
		['Set the starting Chips'] = 'Set the starting Chips',
		['Blind increase percent per round'] = 'Blind increase percent per round',
		['Set the by what percent the Blind increases each round'] = 'Set the by what percent the Blind increases each round',
		['Starting Blind'] = 'Starting Blind',
		['Set the starting Blind'] = 'Set the starting Blind',
		['Blinds'] = 'Blinds',
		['Small Blind'] = 'Small Blind',
		['Big Blind'] = 'Big Blind',
		['Checked'] = 'Checked',
		['Called'] = 'Called',
		['Raised'] = 'Raised',
		['Playing'] = 'Playing',
		['Sitting Out'] = 'Sitting Out',
		['Winner!'] = 'Winner!',
		['Default'] = 'Default',
		['Showdown'] = 'Showdown',
		['%s sits %s in Seat %d'] = '%s sits %s in Seat %d',
		['Your turn'] = 'Your turn',
		['Minimap Icon'] = 'Minimap Icon',
		['Turn minimap icon on/off'] = 'Turn minimap icon on/off',
		['%s has no seat available for you'] = '%s has no seat available for you',
		['%s is a dealer and has %s seats available'] = '%s is a dealer and has %s seats available',
		['%s has client version %s'] = '%s has client version %s',
		['Autoplay'] = 'Autoplay',
		['Call any'] = 'Call any',
		['Sticky'] = 'Sticky',
		['Empty'] = 'Empty',
	}
	,
	{__index = function(self, key)
		if debug then ChatFrame3:AddMessage('Please localize: '..tostring(key)) end
		rawset(self, key, key)
		return key
	end
	}
)
