if( 0 ~= 0) then return end

local debug = false

MyLocalization = setmetatable(
	{
		['WoW Poker Lerduzz'] = 'WoW Poker Lerduzz',
		['Quit'] = 'Quit',
		['Sit Out'] = 'Sit Out',
		['Play'] = 'Play',
		['Fold'] = 'Fold',
		['Call'] = 'Call',
		['All In'] = 'All In',
		['Raise'] = 'Raise',
		['Clear Chips'] = 'Clear Chips',
		['Chips'] = 'Chips',
		['+100 Chips'] = '+100 Chips',
		['Boot'] = 'Boot',
		['Ok'] = 'Ok',
		
		['Two'] = 'Two',
		['Three'] = 'Three',
		['Four'] = 'Four',
		['Five'] = 'Five',
		['Six'] = 'Six',
		['Seven'] = 'Seven',
		['Eight'] = 'Eight',
		['Nine'] = 'Nine',
		['Ten'] = 'Ten',
		['Jack'] = 'Jack',
		['Queen'] = 'Queen',
		['King'] = 'King',
		['Ace'] = 'Ace',
		['Twos'] = 'Twos',
		['Threes'] = 'Threes',
		['Fours'] = 'Fours',
		['Fives'] = 'Fives',
		['Sixes'] = 'Sixs',
		['Sevens'] = 'Sevens',
		['Eights'] = 'Eights',
		['Nines'] = 'Nines',
		['Tens'] = 'Tens',
		['Jacks'] = 'Jacks',
		['Queens'] = 'Queens',
		['Kings'] = 'Kings',
		['Aces'] = 'Aces',	
		
		['High Card'] = 'High Card',
		['1 Pair'] = '1 Pair',
		['2 Pair: %s, %s'] = '2 Pair: %s, %s',
		['3 of a Kind'] = '3 of a Kind',
		['Straight: %s (high)'] = 'Straight: %s (high)',
		['Flush: %s (high)'] = 'Flush: %s (high)',
		['Full House: %s, %s'] = 'Full House: %s, %s',
		['4 of a Kind'] = '4 of a Kind',
		['Straight Flush: %s (high)'] = 'Straight Flush: %s (high)',
		['Royal Flush'] = 'Royal Flush',
		
		["Do you wish to start Dealing?"] = 'Do you wish to start Dealing?',
		["To join a game use '/poker dealer <playername>'"] = "To join a game use '/poker dealer <playername>'",
		['Start Dealing'] = 'Start Dealing',
		['Cancel'] = 'Cancel',
		['Options'] = 'Options',
		['a Fork of AnzacHoldem'] = 'a Fork of AnzacHoldem',
		['Use \'/poker\' to start a table as the dealer.'] = 'Use \'/poker\' to start a table as the dealer.',
		['Use \'/poker dealer <playername>\' to join someone elses table.'] = 'Use \'/poker dealer <playername>\' to join someone elses table.',
		['Use \'/poker artwork <number>\' to set artwork.'] = 'Use \'/poker artwork <number>\' to set artwork.',
		['Use \'/poker blind <number>\' to set starting blind.'] = 'Use \'/poker blind <number>\' to set starting blind.',
		['Use \'/poker increase <percent>\' to set blind increment percent.'] = 'Use \'/poker increase <percent>\' to set blind increment percent.',
		['Use \'/poker options\' for options panel'] = 'Use \'/poker options\' for options panel',
		['AutoDealing'] = 'AutoDealing',
		['I\'m Back'] = 'I\'m Back',
		['Sit Out'] = 'Sit Out',
		['Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal.'] = 'Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal.',
		['Show Cards'] = 'Show Cards',
		['%s has seated you in Seat %d'] = '%s has seated you in Seat %d',
		['Check'] = 'Check',
		['Use just /poker instead'] = 'Use just /poker instead',
		['You did not act in time. Press I\'m Back to continue playing.'] = 'You did not act in time. Press I\'m Back to continue playing.',
		['has left the table.'] = 'has left the table.',
		['The dealer booted you.'] = 'The dealer booted you.',
		['has quit. GG.'] = 'has quit. GG.',
		['You are now a dealer.'] = 'You are now a dealer.',
		['Total Pot'] = 'Total Pot',
		['wins'] = 'wins',
		['Split'] = 'Split',
		['No Winners. Game Seed = '] = 'No Winners. Game Seed = ',
		['Error case'] = 'Error case',
		['Player Invalid Action'] = 'Player Invalid Action',
		['Cannot boot the dealer.'] = 'Cannot boot the dealer.',
		['Folded'] = 'Folded',
		['Showing'] = 'Showing',
		['No such player'] = 'No such player',
		['Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal.'] = 'Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal.',
		['WoW Poker Lerduzz Options'] = 'WoW Poker Lerduzz Options',
		['These options are saved between sessions'] = 'These options are saved between sessions',
		['Neutral'] = 'Neutral',
		['Alliance'] = 'Alliance',
		['Horde'] = 'Horde',
		['Original'] = 'Original',
		['Artwork'] = 'Artwork',
		['Select card back artwork'] = 'Select card back artwork',
		['Starting Chips'] = 'Starting Chips',
		['Set the starting Chips'] = 'Set the starting Chips',
		['Blind increase percent per round'] = 'Blind increase percent per round',
		['Set the by what percent the Blind increases each round'] = 'Set the by what percent the Blind increases each round',
		['Starting Blind'] = 'Starting Blind',
		['Set the starting Blind'] = 'Set the starting Blind',
		['Blinds'] = 'Blinds',
		['Small Blind'] = 'Small Blind',
		['Big Blind'] = 'Big Blind',
		['Checked'] = 'Checked',
		['Called'] = 'Called',
		['Raised'] = 'Raised',
		['Playing'] = 'Playing',
		['Sitting Out'] = 'Sitting Out',
		['Winner!'] = 'Winner!',
		['Default'] = 'Default',
		['Showdown'] = 'Showdown',
		['Next Round\'s Big Blind'] = 'Next Round\'s Big Blind',
		['Current Blind Increment per round'] = 'Current Blind Increment per round',
		['%s sits %s in Seat %d'] = '%s sits %s in Seat %d',
		['Your turn'] = 'Your turn',
		['Minimap Icon'] = 'Minimap Icon',
		['Turn minimap icon on/off'] = 'Turn minimap icon on/off',
		['%s has no seat available for you'] = '%s has no seat available for you',
		['%s is a dealer and has %s seats available'] = '%s is a dealer and has %s seats available',
		['%s has client version %s'] = '%s has client version %s',
		['Use \'/poker dealers\' to find dealers in your guild/party/raid.'] = 'Use \'/poker dealers\' to find dealers in your guild/party/raid.',
		['Use \'/poker clients\' to find clients in your guild/party/raid.'] = 'Use \'/poker clients\' to find clients in your guild/party/raid.',
		['Use \'/poker help\' for slash command options'] = 'Use \'/poker help\' for slash command options',
		['Looking for dealers'] = 'Looking for dealers',
		['Looking for clients'] = 'Looking for clients',
		['Tick to act automatically'] = 'Tick to automatically act',
		['Call any'] = 'Call any',
		['Sticky'] = 'Sticky',
		['Empty'] = 'Empty',
	}
	,
	{__index = function(self, key)
		if debug then ChatFrame3:AddMessage('Please localize: '..tostring(key)) end
		rawset(self, key, key)
		return key
	end
	}
)
