if( 0 ~= 0) then return end

local debug = false

MyLocalization = setmetatable(
	{
		['WoW Poker Lerduzz'] = 'WoW Poker Lerduzz',
		['Quit'] = 'Salir',
		['Sit Out'] = 'Levantarse',
		['Play'] = 'Jugar',
		['Fold'] = 'Retirarse',
		['Call'] = 'Igualar',
		['All In'] = 'Jugar todo',
		['Raise'] = 'Subir',
		['Chips'] = 'Fichas',

		['Two'] = 'Dos',
		['Three'] = 'Tres',
		['Four'] = 'Cuatro',
		['Five'] = 'Cinco',
		['Six'] = 'Seis',
		['Seven'] = 'Siete',
		['Eight'] = 'Ocho',
		['Nine'] = 'Nueve',
		['Ten'] = 'Diez',
		['Jack'] = 'Jota',
		['Queen'] = 'Reina',
		['King'] = 'Rey',
		['Ace'] = 'As',
		['Twos'] = 'Dos',
		['Threes'] = 'Tres',
		['Fours'] = 'Cuatros',
		['Fives'] = 'Cincos',
		['Sixes'] = 'Seis',
		['Sevens'] = 'Sietes',
		['Eights'] = 'Ochos',
		['Nines'] = 'Nueves',
		['Tens'] = 'Diez',
		['Jacks'] = 'Jotas',
		['Queens'] = 'Reinas',
		['Kings'] = 'Reyes',
		['Aces'] = 'Ases',
		
		['High Card'] = 'Carta Alta',
		['1 Pair'] = 'Pareja',
		['2 Pair: %s, %s'] = 'Doble Pareja: %s, %s',
		['3 of a Kind'] = 'Trío',
		['Straight: %s (high)'] = 'Escalera: %s (carta mayor)',
		['Flush: %s (high)'] = 'Color: %s (carta mayor)',
		['Full House: %s, %s'] = 'Full: %s, %s',
		['4 of a Kind'] = 'Poker',
		['Straight Flush: %s (high)'] = 'Escalera de Color: %s (carta mayor)',
		['Royal Flush'] = 'Escalera Real',
		
		["Do you want to start the game?"] = '¿Deseas comenzar la partida?',
		['Start'] = 'Comenzar',
		['Cancel'] = 'Cancelar',
		['Options'] = 'Opciones',
		['I\'m Back'] = 'I\'m Back',
		['Sit Out'] = 'Pararse',
		['Show Cards'] = 'Mostrar Cartas',
		['%s has seated you in Seat %d'] = '%s has seated you in Seat %d',
		['Check'] = 'Pasar',
		['Use just /poker instead'] = 'Use just /poker instead',
		['You did not act in time. Press I\'m Back to continue playing.'] = 'You did not act in time. Press I\'m Back to continue playing.',
		['has left the table.'] = 'has left the table.',
		['Total Pot'] = 'Apuesta Total',
		['wins'] = 'ha ganado',
		['Split'] = 'Split',
		['Folded'] = 'Retirado',
		['Showing'] = 'Mostrando',
		['No such player'] = 'No se encuentra el jugador',
		['WoW Poker Lerduzz Options'] = 'Opciones de WoW Poker Lerduzz',
		['These options are saved between sessions'] = 'Estas opciones son guardadas entre sesiones',
		['Starting Chips'] = 'Fichas Iniciales',
		['Set the starting Chips'] = 'Establezca las fichas iniciales',
		['Blind increase percent per round'] = 'Incremento de ciega por ronda',
		['Set the by what percent the Blind increases each round'] = 'Establezca el porcentaje de aumento de ciegas por ronda',
		['Starting Blind'] = 'Ciega Inicial',
		['Set the starting Blind'] = 'Establezca la ciega inicial',
		['Blinds'] = 'Ciegas',
		['Small Blind'] = 'Ciega Pequeña',
		['Big Blind'] = 'Ciega Grande',
		['Checked'] = 'Pasado',
		['Called'] = 'Igualado',
		['Raised'] = 'Subido',
		['Playing'] = 'Jugando',
		['Sitting Out'] = 'Sitting Out',
		['Winner!'] = 'Ganador!',
		['Default'] = 'Predeterminado',
		['Showdown'] = 'Showdown',
		['%s sits %s in Seat %d'] = '%s sits %s in Seat %d',
		['Your turn'] = 'Tu turno',
		['Minimap Icon'] = 'Ícono en radar',
		['Turn minimap icon on/off'] = 'Activa o desactiva el ícono en el minimapa (recomendado)',
		['%s has no seat available for you'] = '%s has no seat available for you',
		['%s is a dealer and has %s seats available'] = '%s is a dealer and has %s seats available',
		['%s has client version %s'] = '%s has client version %s',
		['Call any'] = 'Igualar todo',
		['Check/Fold'] = 'Pasar/Retirarse',
		['Sticky'] = 'Mantener',
		['Empty'] = 'Nada',
	}
	,
	{__index = function(self, key)
		if debug then ChatFrame3:AddMessage('Please localize: '..tostring(key)) end
		rawset(self, key, key)
		return key
	end
	}
)
